import type { MapCategory, MapCategoryId } from '~/types/map'

const ICONS_BASE = 'https://cdn.wynn.tools'

export const CATEGORIES: MapCategory[] = [
  // Places
  {
    id: 'wynntils:place:province',
    parentId: null,
    label: 'Provinces',
    icon: `${ICONS_BASE}/icons/map/sign.png`,
    color: '#9aeb53',
    defaultOn: true,
    minZoom: -3,
    cluster: false,
  },
  {
    id: 'wynntils:place:city',
    parentId: null,
    label: 'Cities',
    icon: `${ICONS_BASE}/icons/map/sign.png`,
    color: '#ffd24a',
    defaultOn: true,
    minZoom: -1,
    cluster: false,
  },
  {
    id: 'wynntils:place:town-or-place',
    parentId: null,
    label: 'Towns & Places',
    icon: `${ICONS_BASE}/icons/map/sign.png`,
    color: '#7adfff',
    defaultOn: true,
    minZoom: 1,
    cluster: false,
  },

  // Content
  {
    id: 'wynntils:content:dungeon',
    parentId: null,
    label: 'Dungeons',
    icon: `${ICONS_BASE}/icons/map/dungeon_entrance.png`,
    color: '#ff7373',
    defaultOn: true,
    minZoom: 0,
    cluster: false,
  },
  {
    id: 'wynntils:content:dungeon:corrupted',
    parentId: 'wynntils:content:dungeon',
    label: 'Corrupted Dungeons',
    icon: `${ICONS_BASE}/icons/map/dungeon_entrance.png`,
    color: '#9b59b6',
    defaultOn: true,
    minZoom: 0,
    cluster: false,
  },
  {
    id: 'wynntils:content:raid',
    parentId: null,
    label: 'Raids',
    icon: `${ICONS_BASE}/icons/map/raid_entrance.png`,
    color: '#ff4d4d',
    defaultOn: true,
    minZoom: 0,
    cluster: false,
  },
  {
    id: 'wynntils:content:boss-altar',
    parentId: null,
    label: 'Boss Altars',
    icon: `${ICONS_BASE}/icons/map/boss_altar.png`,
    color: '#c084fc',
    defaultOn: true,
    minZoom: 1,
    cluster: false,
  },
  {
    id: 'wynntils:content:cave',
    parentId: null,
    label: 'Caves',
    icon: `${ICONS_BASE}/icons/map/cave.png`,
    color: '#6b7280',
    defaultOn: false,
    minZoom: 1,
    cluster: true,
  },
  {
    id: 'wynntils:content:lootrun-camp',
    parentId: null,
    label: 'Lootrun Camps',
    icon: `${ICONS_BASE}/icons/map/lootrun_camp.png`,
    color: '#fbbf24',
    defaultOn: true,
    minZoom: 0,
    cluster: false,
  },
  {
    id: 'wynntils:content:grind-spot',
    parentId: null,
    label: 'Grind Spots',
    icon: `${ICONS_BASE}/icons/map/grind_spot.png`,
    color: '#6b9e6b',
    defaultOn: false,
    minZoom: 1,
    cluster: false,
  },
  {
    id: 'wynntils:content:shrine',
    parentId: null,
    label: 'Rune Shrines',
    icon: `${ICONS_BASE}/icons/map/shrine.png`,
    color: '#f59e0b',
    defaultOn: true,
    minZoom: 1,
    cluster: false,
  },

  // Services — standalone
  {
    id: 'wynntils:service:blacksmith',
    parentId: null,
    label: 'Blacksmith',
    icon: `${ICONS_BASE}/icons/map/blacksmith.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:booth-shop',
    parentId: null,
    label: 'Booth Shops',
    icon: `${ICONS_BASE}/icons/map/booth_shop.png`,
    color: '#a78bfa',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:fast-travel',
    parentId: null,
    label: 'Fast Travel',
    icon: `${ICONS_BASE}/icons/map/fast_travel.png`,
    color: '#22d3ee',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:housing-balloon',
    parentId: null,
    label: 'Housing Balloons',
    icon: `${ICONS_BASE}/icons/map/housing_balloon.png`,
    color: '#f472b6',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:identifier',
    parentId: null,
    label: 'Item Identifier',
    icon: `${ICONS_BASE}/icons/map/item_identifier.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:party-finder',
    parentId: null,
    label: 'Party Finder',
    icon: `${ICONS_BASE}/icons/map/party_finder.png`,
    color: '#4ade80',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:item-upgrader',
    parentId: null,
    label: 'Item Upgrader',
    icon: `${ICONS_BASE}/icons/map/item_upgrader.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:mount-enclosure',
    parentId: null,
    label: 'Mount Enclosures',
    icon: `${ICONS_BASE}/icons/map/mount_enclosure.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:seaskipper',
    parentId: null,
    label: 'Seaskipper',
    icon: `${ICONS_BASE}/icons/map/seaskipper.png`,
    color: '#60a5fa',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:trade-market',
    parentId: null,
    label: 'Trade Market',
    icon: `${ICONS_BASE}/icons/map/trade_market.png`,
    color: '#fbbf24',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },

  // Services — merchant group
  {
    id: 'wynntils:service:merchant',
    parentId: null,
    label: 'Merchants',
    icon: `${ICONS_BASE}/icons/map/armor_merchant.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
    virtual: true,
  },
  {
    id: 'wynntils:service:merchant:armor',
    parentId: 'wynntils:service:merchant',
    label: 'Armor Merchants',
    icon: `${ICONS_BASE}/icons/map/armor_merchant.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:merchant:weapon',
    parentId: 'wynntils:service:merchant',
    label: 'Weapon Merchants',
    icon: `${ICONS_BASE}/icons/map/weapon_merchant.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:merchant:potion',
    parentId: 'wynntils:service:merchant',
    label: 'Potion Merchants',
    icon: `${ICONS_BASE}/icons/map/potion_merchant.png`,
    color: '#a78bfa',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:merchant:scroll',
    parentId: 'wynntils:service:merchant',
    label: 'Scroll Merchants',
    icon: `${ICONS_BASE}/icons/map/scroll_merchant.png`,
    color: '#a78bfa',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:merchant:dungeon',
    parentId: 'wynntils:service:merchant',
    label: 'Dungeon Merchants',
    icon: `${ICONS_BASE}/icons/map/dungeon_merchant.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:merchant:dungeon-scroll',
    parentId: 'wynntils:service:merchant',
    label: 'Dungeon Scroll Merchants',
    icon: `${ICONS_BASE}/icons/map/dungeon_scroll_merchant.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:merchant:emerald',
    parentId: 'wynntils:service:merchant',
    label: 'Emerald Merchants',
    icon: `${ICONS_BASE}/icons/map/emerald_merchant.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:merchant:liquid-emerald',
    parentId: 'wynntils:service:merchant',
    label: 'Liquid Emerald Merchants',
    icon: `${ICONS_BASE}/icons/map/liquid_merchant.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:merchant:tool',
    parentId: 'wynntils:service:merchant',
    label: 'Tool Merchants',
    icon: `${ICONS_BASE}/icons/map/tool_merchant.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:merchant:exchange',
    parentId: 'wynntils:service:merchant',
    label: 'Exchange Merchants',
    icon: `${ICONS_BASE}/icons/map/exchange_merchant.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:merchant:mount',
    parentId: 'wynntils:service:merchant',
    label: 'Mount Merchants',
    icon: `${ICONS_BASE}/icons/map/mount_merchant.png`,
    color: '#94a3b8',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },

  // Services — profession group
  {
    id: 'wynntils:service:profession',
    parentId: null,
    label: 'Profession Stations',
    icon: `${ICONS_BASE}/icons/map/alchemist_station.png`,
    color: '#8b5cf6',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
    virtual: true,
  },
  {
    id: 'wynntils:service:profession:alchemism',
    parentId: 'wynntils:service:profession',
    label: 'Alchemism Stations',
    icon: `${ICONS_BASE}/icons/map/alchemist_station.png`,
    color: '#8b5cf6',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:profession:armoring',
    parentId: 'wynntils:service:profession',
    label: 'Armoring Stations',
    icon: `${ICONS_BASE}/icons/map/armoring_station.png`,
    color: '#8b5cf6',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:profession:weaponsmithing',
    parentId: 'wynntils:service:profession',
    label: 'Weaponsmithing Stations',
    icon: `${ICONS_BASE}/icons/map/weaponsmithing_station.png`,
    color: '#8b5cf6',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:profession:tailoring',
    parentId: 'wynntils:service:profession',
    label: 'Tailoring Stations',
    icon: `${ICONS_BASE}/icons/map/tailoring_station.png`,
    color: '#8b5cf6',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:profession:woodworking',
    parentId: 'wynntils:service:profession',
    label: 'Woodworking Stations',
    icon: `${ICONS_BASE}/icons/map/woodworking_station.png`,
    color: '#8b5cf6',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:profession:scribing',
    parentId: 'wynntils:service:profession',
    label: 'Scribing Stations',
    icon: `${ICONS_BASE}/icons/map/scribing_station.png`,
    color: '#8b5cf6',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:profession:jeweling',
    parentId: 'wynntils:service:profession',
    label: 'Jeweling Stations',
    icon: `${ICONS_BASE}/icons/map/jeweling_station.png`,
    color: '#8b5cf6',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
  {
    id: 'wynntils:service:profession:cooking',
    parentId: 'wynntils:service:profession',
    label: 'Cooking Stations',
    icon: `${ICONS_BASE}/icons/map/cooking_station.png`,
    color: '#8b5cf6',
    defaultOn: false,
    minZoom: 0,
    cluster: true,
  },
]

const byId = new Map(CATEGORIES.map(c => [c.id, c]))

export function getCategory(id: MapCategoryId): MapCategory | null {
  return byId.get(id) ?? null
}

export function getChildCategories(parentId: MapCategoryId): MapCategory[] {
  return CATEGORIES.filter(c => c.parentId === parentId)
}

export function defaultEnabledCategories(): MapCategoryId[] {
  return CATEGORIES.filter(c => c.defaultOn).map(c => c.id)
}

export function isServiceCategory(id: MapCategoryId): boolean {
  return id.startsWith('wynntils:service:')
}

export function isContentCategory(id: MapCategoryId): boolean {
  return id.startsWith('wynntils:content:')
}

export function isPlaceCategory(id: MapCategoryId): boolean {
  return id.startsWith('wynntils:place:')
}
