name: Stale

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue has been inactive for 60 days and will be closed in 14 days unless there is new activity."
          stale-issue-label: stale
          days-before-issue-stale: 60
          days-before-issue-close: 14
          days-before-pr-stale: -1
          days-before-pr-close: -1
